### ISSUE TITLE
Select selected attribute not working

### ISSUE THREAD

**Issue by Emerson** [Emerson/ember-form-master-2000#4]

**Comment by angusfretwell** [comment]
Any chance this will be fixed any time soon?

**Comment by angusfretwell** [comment]
Oh, seems like it was fixed in 06ed2cf96c3a39bded122a39545a6f4f80514da4.

Is there any chance you could apply 06ed2cf96c3a39bded122a39545a6f4f80514da4 as well as 67142065629964ea56cf507c9b8b5fc9bac19682 and generate a release? I've tried installing what's on master, however, as I'm using Ember 1.13, it breaks due to 630ba2a54e29c7e786a156d15f28c223714a4df9 (throws an error about `this.attrs.action()`).

**Comment by g-cassie** [comment]
@angusfretwell we should keep master compatible with 1.x - if you want to make a PR to fix the `this.attrs` problem in 1.13 I can merge it to master

**Comment by Emerson** [comment]
I'm not sure things are compatible with 1.13 as it stands... but definitely agree with the sentiment.

**Comment by angusfretwell** [comment]
@g-cassie @Emerson I'm a bit flat out at the moment, but I will have a go at getting master working on 1.13 when I get some downtime :smile:

**Comment by g-cassie** [comment]
@angusfretwell @Emerson Is there some solution for testing against multiple versions of Ember?

**Comment by angusfretwell** [comment]
@g-cassie Not sure, but [ember-try](https://github.com/kategengler/ember-try) seems promising?

**Comment by g-cassie** [comment]
@Emerson If you want to wait to release until early next week I can try to get this fixed so 1.13 is working...

**Comment by Emerson** [comment]
I think it might be more than just this that is preventing 1.13 compatibility. It almost seems like maintaining two separate libraries. Basic things like how we write tests, how we export handlebar helpers, and probably a bunch of other issues. Would love to hear what you run into when you boot up 1.13.

**Comment by g-cassie** [comment]
This is fixed in 3.0.0
